name: Build Hugo Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: 'true'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 使用 LTS 版本的 Node.js

      - name: Install dependencies
        run: npm install --prefix ./themes/tailbliss

      - name: Build Hugo Site
        run: hugo --minify

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-public-folder
          path: public/